# Generated by Django 4.2 on 2024-02-27 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vacaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacaciones',
            options={'verbose_name': 'Vacaciones', 'verbose_name_plural': 'Vacaciones'},
        ),
        migrations.CreateModel(
            name='AfectacionPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('afectacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.afectacion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
            ],
            options={
                'verbose_name': 'Afectacion_Persona',
                'verbose_name_plural': 'Afectaciones_Persona',
            },
        ),
    ]
