# Generated by Django 4.2 on 2024-02-27 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_vacaciones_options_afectacionpersona'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
            ],
            options={
                'verbose_name': 'Categoria_Persona',
                'verbose_name_plural': 'Categoria_Persona',
            },
        ),
    ]
