# Generated by Django 4.2 on 2024-02-27 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_categoriapersona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.posicion')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turno')),
            ],
            options={
                'verbose_name': 'Rotación',
                'verbose_name_plural': 'Rotaciones',
            },
        ),
    ]
