# Generated by Django 4.2 on 2024-02-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rotacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='tipo',
            field=models.CharField(choices=[(1, '8 horas'), (2, '12 horas')], max_length=2),
        ),
    ]
