# Generated by Django 4.2 on 2024-02-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_turno_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='tipo',
            field=models.IntegerField(choices=[(1, '8 horas'), (2, '12 horas')]),
        ),
    ]
