# Generated by Django 4.2 on 2024-02-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_turno_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='disponible',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='instructor',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
