# Generated by Django 4.2 on 2024-02-28 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_persona_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turno')),
            ],
            options={
                'verbose_name': 'Brigada',
                'verbose_name_plural': 'Brigadas',
            },
        ),
    ]
