# Generated by Django 4.2 on 2024-03-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_brigada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afectacionpersona',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
    ]
