# Generated by Django 4.2 on 2024-03-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_afectacionpersona_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotacion',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
            preserve_default=False,
        ),
    ]
