# Generated by Django 4.2 on 2024-03-07 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rotacion_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescansoPlanificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
            ],
            options={
                'verbose_name': 'Descanso Planificado',
                'verbose_name_plural': 'Descansos Planificados',
            },
        ),
        migrations.DeleteModel(
            name='Vacaciones',
        ),
    ]
